sudo: required
os: linux
language: minimal
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4
services:
  - docker

before_install:
  - docker pull lacledeslan/gamesvr-goldsource

script:
  - docker version
  - docker build --no-cache --tag lltest/gamesvr-goldsource-dmc --tag lacledeslan/gamesvr-goldsource-dmc --build-arg BUILDNODE=TravisCI --build-arg SOURCE_COMMIT="$TRAVIS_COMMIT" -f Dockerfile.linux .
  - docker run -it --rm lltest/gamesvr-goldsource-dmc ./ll-tests/gamesvr-goldsource-dmc.sh

notifications:
  slack:
    secure: 7aqAGTcCguHwvCwJLoLAQ19FXKHODy2+O50dF+YnpX5nIqZTKH3SzIgqURVjTINPqZJ/p1pJEpxGMvGScSbO3eErYi8nA6CkMKCjVJb6WXOtvQvp3QrL1uCMhrc5EQE1+P/eMY7subPdIwYlBkavWYNNbpmfwNiyeh0rRSIqpJH0Ckk+8rRtxlgXfZ9wz/1+XAIb3J2CMzjlBZytoB6bcOFN8y4zAHe/freK9gcJxjJ0kLbdNA8Sh0OXlDYBkrcGCTdpYPmKs3JTwxxPwc5AhTRhqDsLUxMbuaLQEZqcc3GL/c7r3hrbyFS9id/0hFEMGb1jXv4dDxUW1TpCbTPAptHPdt5fM7sSOYDp2hxoKT7repG5ZJze+YOyv7nn8XNaHljG7vQvRA4ghnJvYacSRqS2Y5g+EX+jPgZGoxpTGx5bPuZPJEbyK83v2rWS8IjX+lrtXjy2fn6GM27klovOfNV/ALbdypa8IBWaVDR9kyPUicHIDIW65z0zVQRAKm0D2kaAs+GF6eSQF7+IhCklLRi/V+Tz68vusMDQEADd6vS6+Yk5bkxAWqljD8PXnIKDQHxDa5twnYZBwX01antvIwCJiY9f5HrqHf4PHGPvQfEoo2xoFRHt0mT+dy0/CR4oOcrznqwkDzQEnbGeXE6MtvBOFOEYcP/XPPplSRQKtMg=

before_deploy:
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin;
deploy:
  provider: script
  script: docker push lacledeslan/gamesvr-goldsource-dmc
  on:
    branch: master
after_deploy:
 - curl -X POST https://hooks.microbadger.com/images/lacledeslan/gamesvr-dods-freeplay/$MICROBADGER_TOKEN
