name: linux/amd64

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch: # Allows action to be run manually from the Actions tab

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Docker HUB Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: lacledeslan/gamesvr-goldsource-dmc
          short-description: "LL Deathmatch Classic Freeplay Server"
          readme-filepath: ./README.md
